const fs = require('fs');
const path = require('path');

const packageName = 'noobs.node';
const distRoot = path.resolve(__dirname, 'dist');
const distBin = path.join(distRoot, 'bin');

// Clean the dist directory if it exists.
if (fs.existsSync(distRoot)) {
  fs.rmSync(distRoot, { recursive: true, force: true });
}

// Remake the dist directory structure.
fs.mkdirSync(distRoot);
fs.mkdirSync(distBin);

// Copy the compiled .node file.
const addonSrc = path.resolve(__dirname, 'build', 'Release', packageName);
const addonDest = path.join(distRoot, packageName);
fs.copyFileSync(addonSrc, addonDest);

if (process.platform === 'win32') {
  // Now copy the .dll files we need.
  const binSrc = path.resolve(__dirname, 'bin', '64bit');
  const binDst = path.resolve(__dirname, 'dist', 'bin');

  fs.readdirSync(binSrc)
    .filter((file) => file.endsWith('.dll'))
    .forEach((file) => {
      const src = path.join(binSrc, file);
      const dst = path.join(binDst, file);
      fs.copyFileSync(src, dst);
    });

  // Copy executable files required.
  const exeFiles = [
    'obs-ffmpeg-mux.exe', // Required for any sort of recording.
    'obs-amf-test.exe',   // For getting AMF encoding capabilities.
    'obs-nvenc-test.exe', // For getting NVENC encoding capabilities.
    'obs-qsv-test.exe',    // For getting QSV encoding capabilities.
    'ffmpeg.exe', // Dynamically linked ffmpeg exe.
    'ffprobe.exe' // Dynamically linked ffprobe exe.
  ];

  exeFiles.forEach((file) => {
    const srcPath = path.resolve(__dirname, 'bin', '64bit', file);
    const destPath = path.resolve(__dirname, 'dist', 'bin', file);
    fs.copyFileSync(srcPath, destPath);
  });

  // Copy plugins themselves.
  const pluginSrc = path.resolve(__dirname, 'bin', 'obs-plugins');
  const pluginDst = path.resolve(__dirname, 'dist', 'obs-plugins');

  fs.cpSync(pluginSrc, pluginDst, {
    recursive: true ,
    filter: (src) => !src.endsWith('.pdb') // Exclude PDB files, they are debug files and they are huge.
  });

  // Copy data, including effects and plugin data.
  const dataSrc = path.resolve(__dirname, 'bin', 'data');
  const dataDst = path.resolve(__dirname, 'dist', 'data');

  fs.cpSync(dataSrc, dataDst, {
    recursive: true,
    filter: (src) => !src.endsWith('.pdb') // Exclude PDB files, they are debug files and they are huge.
  });
} else if (process.platform === 'darwin') {
  // Copy the macOS runtime generated by scripts/build-libobs-mac.sh.
  const macSources = [
    { name: 'Frameworks', src: path.resolve(__dirname, 'Frameworks') },
    { name: 'PlugIns',   src: path.resolve(__dirname, 'PlugIns')   },
    { name: 'data',      src: path.resolve(__dirname, 'data')      },
  ];
  // Keep framework symlinks relative; fs.cpSync can rewrite them.
  const { execFileSync } = require('child_process');
  const adHocSign = (file) => {
    try {
      execFileSync('codesign', ['--force', '--sign', '-', file], { stdio: 'inherit' });
      console.log(`[dist] ad-hoc signed ${path.relative(distRoot, file)}`);
    } catch (err) {
      console.warn(`[dist] codesign on ${file} failed:`, err.message);
    }
  };

  for (const { name, src } of macSources) {
    if (!fs.existsSync(src)) {
      console.warn(`[dist] missing ${name}/ - run scripts/build-libobs-mac.sh first`);
      continue;
    }
    const dst = path.join(distRoot, name);
    execFileSync('cp', ['-R', src, dst], { stdio: 'inherit' });
    console.log(`[dist] copied ${name}/ -> dist/${name}/`);
  }

  // Point plugin @rpath lookups at dist/Frameworks.
  const pluginsDir = path.join(distRoot, 'PlugIns');
  if (fs.existsSync(pluginsDir)) {
    for (const entry of fs.readdirSync(pluginsDir)) {
      if (!entry.endsWith('.plugin')) continue;
      const name = entry.replace(/\.plugin$/, '');
      const bin = path.join(pluginsDir, entry, 'Contents', 'MacOS', name);
      if (!fs.existsSync(bin)) continue;
      try {
        execFileSync('install_name_tool', ['-add_rpath', '@loader_path/../../../../Frameworks', bin], { stdio: 'inherit' });
        console.log(`[dist] patched ${name} plugin rpath`);
        adHocSign(bin);
      } catch (err) {
        console.warn(`[dist] install_name_tool on ${name} failed:`, err.message);
      }
    }
  }

  const libobs = path.join(distRoot, 'Frameworks', 'libobs.framework', 'Versions', 'A', 'libobs');
  if (fs.existsSync(libobs)) {
    // Point libobs @rpath lookups at sibling dylibs in dist/Frameworks.
    try {
      execFileSync('install_name_tool', ['-add_rpath', '@loader_path/../../..', libobs], { stdio: 'inherit' });
      console.log('[dist] patched libobs rpath to @loader_path/../../..');
      adHocSign(libobs);
    } catch (err) {
      console.warn('[dist] install_name_tool failed (already patched?):', err.message);
    }
  }

  // Avoid framework symlinks that electron-builder does not copy reliably.
  // Keep Resources real for NSBundle lookup.
  const fwRoot = path.join(distRoot, 'Frameworks', 'libobs.framework');
  if (fs.existsSync(fwRoot)) {
    for (const link of ['Headers', 'libobs']) {
      const p = path.join(fwRoot, link);
      try {
        const st = fs.lstatSync(p);
        if (st.isSymbolicLink()) {
          fs.unlinkSync(p);
        }
      } catch { /* not present, fine */ }
    }
    const currentLink = path.join(fwRoot, 'Versions', 'Current');
    try {
      const st = fs.lstatSync(currentLink);
      if (st.isSymbolicLink()) {
        fs.unlinkSync(currentLink);
        console.log('[dist] stripped libobs.framework/Versions/Current symlink');
      }
    } catch { /* not present, fine */ }

    const resources = path.join(fwRoot, 'Resources');
    const versionedResources = path.join(fwRoot, 'Versions', 'A', 'Resources');
    fs.rmSync(resources, { recursive: true, force: true });
    if (fs.existsSync(versionedResources)) {
      fs.cpSync(versionedResources, resources, { recursive: true });
      console.log('[dist] copied libobs.framework/Resources for NSBundle lookup');
    }
  }
} else {
  console.warn('[dist] platform not supported:', process.platform);
}
